import json
import time
import uuid
from typing import Any, Dict, List, Optional


ACTIVE_JOB_STATUSES = ("queued", "running")


def now_ts() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


class JobStore:
    """Durable project job/progress store backed by the existing app database."""

    def __init__(self, dm):
        self.dm = dm

    def ensure_schema(self, conn) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS jobs (
                id TEXT PRIMARY KEY,
                project_id INTEGER NOT NULL,
                job_type TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'queued',
                payload_json TEXT NOT NULL DEFAULT '{}',
                error_message TEXT DEFAULT '',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                started_at TEXT,
                finished_at TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS job_steps (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id TEXT NOT NULL,
                step_index INTEGER NOT NULL,
                label TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                detail TEXT DEFAULT '',
                started_at REAL,
                ended_at REAL,
                updated_at TEXT NOT NULL,
                UNIQUE(job_id, step_index)
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_jobs_project_status ON jobs(project_id, status, created_at)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_job_steps_job ON job_steps(job_id, step_index)")

    def create_job(
        self,
        project_id: int,
        job_type: str,
        labels: List[str],
        payload: Optional[Dict[str, Any]] = None,
        job_id: Optional[str] = None,
        status: str = "queued",
    ) -> str:
        jid = job_id or uuid.uuid4().hex
        ts = now_ts()
        with self.dm._db_lock:
            conn = self.dm._get_conn()
            try:
                with conn:
                    self.ensure_schema(conn)
                    conn.execute(
                        """
                        INSERT INTO jobs
                            (id, project_id, job_type, status, payload_json, created_at, updated_at)
                        VALUES (?, ?, ?, ?, ?, ?, ?)
                        """,
                        (jid, int(project_id), job_type, status, json.dumps(payload or {}, ensure_ascii=False), ts, ts),
                    )
                    for idx, label in enumerate(labels):
                        conn.execute(
                            """
                            INSERT INTO job_steps (job_id, step_index, label, status, detail, updated_at)
                            VALUES (?, ?, ?, 'pending', '', ?)
                            """,
                            (jid, idx, str(label), ts),
                        )
            finally:
                conn.close()
        return jid

    def project_has_active_job(self, project_id: int, job_types: Optional[List[str]] = None) -> bool:
        statuses = ",".join("?" for _ in ACTIVE_JOB_STATUSES)
        params: List[Any] = [int(project_id), *ACTIVE_JOB_STATUSES]
        type_clause = ""
        if job_types:
            type_clause = " AND job_type IN (%s)" % ",".join("?" for _ in job_types)
            params.extend(job_types)
        with self.dm._db_lock:
            conn = self.dm._get_conn()
            try:
                self.ensure_schema(conn)
                row = conn.execute(
                    f"SELECT COUNT(*) FROM jobs WHERE project_id = ? AND status IN ({statuses}){type_clause}",
                    params,
                ).fetchone()
                return bool(row and row[0])
            finally:
                conn.close()

    def mark_running(self, job_id: str) -> None:
        ts = now_ts()
        with self.dm._db_lock:
            conn = self.dm._get_conn()
            try:
                with conn:
                    conn.execute(
                        "UPDATE jobs SET status = 'running', started_at = COALESCE(started_at, ?), updated_at = ? WHERE id = ?",
                        (ts, ts, job_id),
                    )
            finally:
                conn.close()

    def update_step(self, job_id: str, step_idx: int, status: str, detail: str = "") -> None:
        ts = now_ts()
        now = time.time()
        with self.dm._db_lock:
            conn = self.dm._get_conn()
            try:
                with conn:
                    row = conn.execute(
                        "SELECT started_at, ended_at FROM job_steps WHERE job_id = ? AND step_index = ?",
                        (job_id, int(step_idx)),
                    ).fetchone()
                    if not row:
                        return
                    started_at, ended_at = row
                    next_started = started_at
                    next_ended = ended_at
                    if status == "running" and not next_started:
                        next_started = now
                    if status == "done" and not next_ended:
                        next_ended = now
                    conn.execute(
                        """
                        UPDATE job_steps
                        SET status = ?, detail = ?, started_at = ?, ended_at = ?, updated_at = ?
                        WHERE job_id = ? AND step_index = ?
                        """,
                        (status, detail or "", next_started, next_ended, ts, job_id, int(step_idx)),
                    )
                    conn.execute("UPDATE jobs SET updated_at = ? WHERE id = ?", (ts, job_id))
            finally:
                conn.close()

    def finish(self, job_id: str, status: str, error_message: str = "") -> None:
        ts = now_ts()
        with self.dm._db_lock:
            conn = self.dm._get_conn()
            try:
                with conn:
                    conn.execute(
                        """
                        UPDATE jobs
                        SET status = ?, error_message = ?, finished_at = ?, updated_at = ?
                        WHERE id = ?
                        """,
                        (status, error_message or "", ts, ts, job_id),
                    )
            finally:
                conn.close()

    def latest_project_progress(self, project_id: int) -> Dict[str, Any]:
        with self.dm._db_lock:
            conn = self.dm._get_conn()
            try:
                self.ensure_schema(conn)
                job = conn.execute(
                    """
                    SELECT id, status, error_message, created_at, started_at, finished_at
                    FROM jobs
                    WHERE project_id = ?
                    ORDER BY
                        CASE status WHEN 'running' THEN 0 WHEN 'queued' THEN 1 ELSE 2 END,
                        created_at DESC
                    LIMIT 1
                    """,
                    (int(project_id),),
                ).fetchone()
                if not job:
                    return {"available": False}
                rows = conn.execute(
                    """
                    SELECT label, status, detail, started_at, ended_at
                    FROM job_steps
                    WHERE job_id = ?
                    ORDER BY step_index ASC
                    """,
                    (job[0],),
                ).fetchall()
            finally:
                conn.close()

        steps = []
        done_count = 0
        running_idx = -1
        for idx, row in enumerate(rows):
            label, status, detail, started_at, ended_at = row
            if status == "done":
                done_count += 1
            if status == "running" and running_idx < 0:
                running_idx = idx
            item = {"label": label, "status": status, "detail": detail or ""}
            if started_at and ended_at:
                item["duration_s"] = round(float(ended_at) - float(started_at), 1)
            elif started_at:
                item["running_s"] = round(time.time() - float(started_at), 1)
            steps.append(item)

        total = len(steps)
        pct = int(done_count / total * 100) if total else 0
        if running_idx >= 0 and total:
            pct = int((done_count + 0.5) / total * 100)
        return {
            "available": True,
            "job_id": job[0],
            "job_status": job[1],
            "error_message": job[2] or "",
            "pct": pct,
            "done_count": done_count,
            "total_steps": total,
            "steps": steps,
        }
